
package org.kie.services.remote.ws.sei.process;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kie.services.remote.ws.wsdl.VersionSO;


/**
 * A simple service example.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProcessService", targetNamespace = ProcessWebService.NAMESPACE)
public interface ProcessWebService {

    static final String NAMESPACE = "http://services.remote.kie.org/process";
    
    @WebMethod(action = "urn:StartProcess")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startProcess", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperStartProcess")
    @ResponseWrapper(localName = "startProcessResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperStartProcessResponse")
    public ProcessInstanceInfo start(@WebParam(name = "procDefIdAndParams", targetNamespace = "") ProcessDefIdAndParameters procDefIdAndParams) throws ProcessWebServiceException;

    @WebMethod(action = "urn:AbortProcess")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abortProcess", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperAbortProcess")
    @ResponseWrapper(localName = "abortProcessResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperAbortProcess")
    public void abort(@WebParam(name = "procInstId", targetNamespace = "") ProcessInstanceId procInstId) throws ProcessWebServiceException;

    @WebMethod(action = "urn:SignalProcess")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signalProcess", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperSignalProcess")
    @ResponseWrapper(localName = "signalProcessResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperSignalProcess")
    public void signal(@WebParam(name = "procInstId", targetNamespace = "") ProcessInstanceId procInstId) throws ProcessWebServiceException;

    @WebMethod(action = "urn:GetProcessInstanceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessInstanceInfo", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperGetProcessInstanceInfo")
    @ResponseWrapper(localName = "getProcessInstanceInfoResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperGetProcessInstanceInfo")
    public ProcessInstanceInfo getInfo(@WebParam(name = "getProcessInstanceInfo", targetNamespace = "") GetProcessInstanceInfo getProcessInstanceInfo) throws ProcessWebServiceException;

    @WebMethod(action = "urn:CompleteWorkItem")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "completeWorkItem", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperCompleteWorkItem")
    @ResponseWrapper(localName = "completeWorkItemResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperCompleteWorkItem")
    public void completeWorkItem(@WebParam(name = "workItemId", targetNamespace = "") WorkItemId workItemId) throws ProcessWebServiceException;

    @WebMethod(action = "urn:AbortWorkItem")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abortWorkItem", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperAbortWorkItem")
    @ResponseWrapper(localName = "abortWorkItemResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperAbortWorkItem")
    public void abortWorkItem(@WebParam(name = "workItemId", targetNamespace = "") WorkItemId workItemId) throws ProcessWebServiceException;

    /**
     * 
     * @return
     *     returns org.kie.services.remote.ws.wsdl.VersionSO
     * @throws ProcessWebServiceException
     */
    @WebMethod(action = "urn:Version")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "version", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperVersion")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperVersionResponse")
    public VersionSO version()
        throws ProcessWebServiceException
    ;

}
