
package org.kie.services.remote.ws.sei.deployment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.kie.services.remote.ws.sei.task.TaskOperationRequest;
import org.kie.services.remote.ws.sei.task.TaskServiceException;


/**
 * A simple service example.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HistoryService", targetNamespace = DeploymentWebService.NAMESPACE)
public interface DeploymentWebService {

    final static String NAMESPACE = "http://services.remote.kie.org/deploy";
    
    @WebMethod(action = "urn:Manage")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "manage", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentId")
    @ResponseWrapper(localName = "manageResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentInfo")
    public DeploymentInfo manage(@WebParam(name = "arg0", targetNamespace = "") DeploymentId arg0) throws TaskServiceException;

    @WebMethod(action = "urn:GetStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentId")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentInfo")
    public DeploymentInfo getStatus(@WebParam(name = "arg0", targetNamespace = "") DeploymentId arg0) throws TaskServiceException;

    @WebMethod(action = "urn:GetStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentId")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentInfo")
    public ProcessIdsResponse getProcessDefinitions(@WebParam(name = "arg0", targetNamespace = "") DeploymentId arg0) throws TaskServiceException;

}
