
package org.kie.services.remote.ws.sei.history;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.kie.services.remote.ws.sei.task.TaskId;
import org.kie.services.remote.ws.sei.task.TaskServiceException;


/**
 * A simple service example.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HistoryService", targetNamespace = "http://services.remote.kie.org/history")
public interface HistoryWebService {

    @WebMethod(action = "urn:Stop")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopTask", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTask")
    @ResponseWrapper(localName = "stopTaskResponse", targetNamespace = "http://services.remote.kie.org/process", className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTaskResponse")
    public void Stop(@WebParam(name = "arg0", targetNamespace = "") TaskId arg0) throws TaskServiceException;

}
