
package org.kie.services.remote.ws.sei.command;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.kie.services.client.serialization.jaxb.impl.JaxbCommandsRequest;
import org.kie.services.client.serialization.jaxb.impl.JaxbCommandsResponse;
import org.kie.services.remote.ws.sei.task.TaskOperationRequest;
import org.kie.services.remote.ws.sei.task.TaskServiceException;


/**
 * A simple service example.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HistoryService", targetNamespace = DeploymentWebService.NAMESPACE)
public interface DeploymentWebService {

    final static String NAMESPACE = "http://services.remote.kie.org/deploy";
    
    @WebMethod(action = "urn:Execute")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "execute", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentId")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperDeploymentInfo")
    public JaxbCommandsResponse execute(@WebParam(name = "arg0", targetNamespace = "") JaxbCommandsRequest arg0) throws TaskServiceException;

}
