
package org.kie.services.remote.ws.sei.history;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.kie.services.remote.ws.sei.task.TaskOperationRequest;
import org.kie.services.remote.ws.sei.task.TaskServiceException;


/**
 * A simple service example.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HistoryService", targetNamespace = HistoryWebService.NAMESPACE)
public interface HistoryWebService {

    final static String NAMESPACE = "http://services.remote.kie.org/history";
    
    @WebMethod(action = "urn:Stop")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopTask", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTask")
    @ResponseWrapper(localName = "stopTaskResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTaskResponse")
    public ProcessInstanceLogResponse findProcessInstanceLogs(@WebParam(name = "arg0", targetNamespace = "") HistoryInstanceLogRequest historyInstLogRequest) throws TaskServiceException;

    @WebMethod(action = "urn:Stop")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopTask", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTask")
    @ResponseWrapper(localName = "stopTaskResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTaskResponse")
    public VariableInstanceLogResponse findVariableInstanceLogs(@WebParam(name = "arg0", targetNamespace = "") HistoryInstanceLogRequest historyInstLogRequest) throws TaskServiceException;

    @WebMethod(action = "urn:Stop")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopTask", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTask")
    @ResponseWrapper(localName = "stopTaskResponse", targetNamespace = NAMESPACE, className = "org.kie.services.remote.ws.wsdl.generated.WrapperStopTaskResponse")
    public NodeInstanceLogResponse findNodeInstanceLogs(@WebParam(name = "arg0", targetNamespace = "") HistoryInstanceLogRequest historyInstLogRequest) throws TaskServiceException;

}
